-- 코드를 작성해주세요
# SELECT ID,
# ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS S,
# MAX(ID) OVER() AS M
# FROM ECOLI_DATA 

SELECT TMP.ID, 
CASE 
WHEN TMP.S > 0.75 * TMP.M THEN 'LOW'
WHEN TMP.S > 0.5 * TMP.M THEN 'MEDIUM'
WHEN TMP.S > 0.25 * TMP.M THEN 'HIGH'
ELSE 'CRITICAL'
END AS COLONY_NAME
FROM (SELECT ID,
ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS S,
MAX(ID) OVER() AS M
FROM ECOLI_DATA) TMP 
ORDER BY TMP.ID