-- 코드를 작성해주세요
 
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
WHERE A.ITEM_NAME NOT IN(SELECT INFO.ITEM_NAME
FROM ITEM_INFO INFO
JOIN ITEM_TREE TREE ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID)
ORDER BY A.ITEM_ID DESC