# -- 코드를 작성해주세요.
# (SELECT FISH_TYPE, MAX(LENGTH)
# FROM FISH_INFO
# GROUP BY FISH_TYPE)

SELECT B.ID, B.FISH_NAME, A.M AS LENGTH
FROM (SELECT FISH_TYPE, MAX(LENGTH) AS M
FROM FISH_INFO
GROUP BY FISH_TYPE) A
JOIN (SELECT *
FROM FISH_INFO
NATURAL JOIN FISH_NAME_INFO) B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.M = B.LENGTH

# SELECT *
# FROM FISH_INFO
# NATURAL JOIN FISH_NAME_INFO